### ISSUE TITLE
request for write permission

### ISSUE THREAD

**Issue by k-okada** [ros-gbp/rqt_pr2_dashboard-release#1]
hi @dirk-thomas @TheClearpathDash 
I am about to release rqt_pr2_dashboard into kinetic with @awesomebytes, can you give us a write permission to this repository?

Thanks in advance.

**Comment by dirk-thomas** [comment]
@k-okada @awesomebytes I invited both of you as admin collaborators on this repo.

**Comment by k-okada** [comment]
@dirk-thomas thanks for the permission on release repository 
One more thing. @TheClearpathDash  @dirk-thomas  Can you give us admin for rqt_pr2_dashboard too?


https://github.com/PR2/rqt_pr2_dashboard/pull/19

**Comment by dirk-thomas** [comment]
Done.

**Comment by k-okada** [comment]
@dirk-thomas thanks and very very sorry to bother you again and again. I found we need pr2_power_drivers to release rqt_pr2_dashboard.

https://github.com/pr2/pr2_power_drivers
https://github.com/pr2-gbp/pr2_power_drivers-release

based on https://github.com/gnoliyil/pr2_kinetic_packages we may need following packages too

https://github.com/PR2/pr2_robot
https://github.com/pr2-gbp/pr2_robot-release
https://github.com/pr2/pr2_controllers
https://github.com/pr2-gbp/pr2_controllers-release
https://github.com/PR2/pr2_ethercat_drivers
https://github.com/pr2-gbp/pr2_ethercat_drivers-release
https://github.com/pr2/pr2_common_actions
https://github.com/pr2-gbp/pr2_common_actions-release
https://github.com/pr2/pr2_apps
https://github.com/pr2-gbp/pr2_apps-release
https://github.com/PR2/pr2_simulator
https://github.com/pr2-gbp/pr2_simulator-release
https://github.com/pr2/pr2_mechanism
https://github.com/pr2-gbp/pr2_mechanism-release
https://github.com/pr2/app_manager
https://github.com/ros-gbp/app_manager-release.git
https://github.com/pr2/willow_maps
https://github.com/ros-gbp/willow_maps-release.git
https://github.com/pr2/pr2_common
https://github.com/pr2-gbp/pr2_common-release

**Comment by dirk-thomas** [comment]
No problem.

* I made you an owner of the `PR2` org unit
* I added you to the `PR2` group of the `ros-gbp` org unit
* I **can't** do anything for the `pr2-gbp` org unit since I am not an owner of that. Maybe @wjwwood help with that since he is an owner.

**Comment by wjwwood** [comment]
I sent @k-okada an invite, but I don't remember which access level I gave you. Email me when you've accepted and I can give you more permissions or create a team or something.

@dirk-thomas do you want me to add you as an owner as well?

**Comment by k-okada** [comment]
@wjwwood thank you for pr2-gbp access, but it seems my access level is "Member", It seems I need to be a "Owner" to push my changes to release repository.

**Comment by dirk-thomas** [comment]
> do you want me to add you as an owner as well?

That would be great, thanks.

**Comment by wjwwood** [comment]
Done and done.

**Comment by k-okada** [comment]
Thanks you , released into kinetic
https://github.com/ros/rosdistro/pull/16972


--
◉ Kei Okada


2018-02-13 15:24 GMT+09:00 William Woodall <notifications@github.com>:

**Comment by k-okada** [comment]
all done https://github.com/PR2/rqt_pr2_dashboard/pull/20#issuecomment-365657928
